CREATE TABLE IF NOT EXISTS "like" (
  "id" SERIAL PRIMARY KEY,
  "userId" INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "postId" INT NOT NULL REFERENCES post(id) ON DELETE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
